import {
  ArrowLeftRight,
  BarChart3,
  Blocks,
  Bot,
  Brain,
  Braces,
  CircleDot,
  ClipboardList,
  Code,
  Crosshair,
  Diamond,
  Dice5,
  Dna,
  Drama,
  Eraser,
  FileText,
  Flag,
  Folders,
  FunctionSquare,
  Gamepad2,
  Gem,
  Globe,
  Hash,
  Image,
  LayoutGrid,
  Library,
  LineChart,
  Link,
  MapPin,
  Microscope,
  NotepadText,
  Package,
  Puzzle,
  Radio,
  RefreshCw,
  Rocket,
  Save,
  Scissors,
  Settings,
  Shield,
  ShieldCheck,
  Shuffle,
  Sparkles,
  Square,
  Tags,
  Target,
  Terminal,
  Timer,
  Eye,
  TreePine,
  TrendingUp,
  Trophy,
  Triangle,
  Type,
  Wrench,
  Zap,
  BookOpen,
} from "lucide-react";

/** Lucide icon registry for learn chapter cards. */
export const CHAPTER_ICONS = {
  settings: Settings,
  package: Package,
  shuffle: Shuffle,
  wrench: Wrench,
  "clipboard-list": ClipboardList,
  "map-pin": MapPin,
  blocks: Blocks,
  gamepad: Gamepad2,
  library: Library,
  trophy: Trophy,
  bot: Bot,
  terminal: Terminal,
  brain: Brain,
  "trending-up": TrendingUp,
  tags: Tags,
  "tree-pine": TreePine,
  "bar-chart": BarChart3,
  "circle-dot": CircleDot,
  microscope: Microscope,
  image: Image,
  refresh: RefreshCw,
  zap: Zap,
  sparkles: Sparkles,
  rocket: Rocket,
  hash: Hash,
  scissors: Scissors,
  radio: Radio,
  triangle: Triangle,
  dice: Dice5,
  globe: Globe,
  flag: Flag,
  "file-text": FileText,
  puzzle: Puzzle,
  notepad: NotepadText,
  gem: Gem,
  building: Blocks,
  code: Code,
  braces: Braces,
  type: Type,
  crosshair: Crosshair,
  "arrow-left-right": ArrowLeftRight,
  square: Square,
  "layout-grid": LayoutGrid,
  "function-square": FunctionSquare,
  "shield-check": ShieldCheck,
  shield: Shield,
  dna: Dna,
  drama: Drama,
  diamond: Diamond,
  folders: Folders,
  target: Target,
  eraser: Eraser,
  link: Link,
  timer: Timer,
  eye: Eye,
  save: Save,
  "line-chart": LineChart,
};

/** Maps legacy emoji / symbol strings from curriculum data to icon keys. */
const LEGACY_ICON_ALIASES = {
  "⚙️": "settings",
  "📦": "package",
  "🔀": "shuffle",
  "🔧": "wrench",
  "📋": "clipboard-list",
  "📍": "map-pin",
  "🏗️": "blocks",
  "🎮": "gamepad",
  "📚": "library",
  "🏆": "trophy",
  "🤖": "bot",
  "🐍": "terminal",
  "🧠": "brain",
  "📈": "trending-up",
  "🏷️": "tags",
  "🌲": "tree-pine",
  "📊": "bar-chart",
  "🔵": "circle-dot",
  "🔬": "microscope",
  "🖼️": "image",
  "🔄": "refresh",
  "⚡": "zap",
  "✨": "sparkles",
  "🚀": "rocket",
  "🔢": "hash",
  "🧱": "blocks",
  "✂️": "scissors",
  "📡": "radio",
  "📐": "triangle",
  "🎲": "dice",
  "🌍": "globe",
  "🏁": "flag",
  "📝": "notepad",
  "🧩": "puzzle",
  "💎": "gem",
  "🐘": "code",
  "🌐": "globe",
  "🛡️": "shield",
  "🔤": "type",
  "🟨": "braces",
  "🗂️": "folders",
  "🎯": "target",
  "🧹": "eraser",
  "🔗": "link",
  "💾": "save",
  "🧬": "dna",
  "🎭": "drama",
  "🔷": "diamond",
  "⌖": "crosshair",
  "⇄": "arrow-left-right",
  "◇": "square",
  "▦": "layout-grid",
  λ: "function-square",
  "✓": "shield-check",
};

export function resolveChapterIconKey(icon) {
  if (!icon || typeof icon !== "string") return "library";
  if (CHAPTER_ICONS[icon]) return icon;
  return LEGACY_ICON_ALIASES[icon] || "library";
}

export function getChapterIconComponent(icon) {
  const key = resolveChapterIconKey(icon);
  return CHAPTER_ICONS[key] || BookOpen;
}
